---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:4.0
        name: redis
        ports:
          - containerPort: 6379
            name: redis
        resources:
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 50Mi
        